package com.piptechnologies.openchat.core.phone

// GENERATED from mledoze/countries (ODbL) by the build tooling; sorted by display name.
// Dial codes are digits only, without the plus. NANP members share "1".

object DialCountries {
    val all: List<DialCountry> = listOf(
        DialCountry(iso2 = "AF", name = "Afghanistan", dialCode = "93"),
        DialCountry(iso2 = "AL", name = "Albania", dialCode = "355"),
        DialCountry(iso2 = "DZ", name = "Algeria", dialCode = "213"),
        DialCountry(iso2 = "AS", name = "American Samoa", dialCode = "1684"),
        DialCountry(iso2 = "AD", name = "Andorra", dialCode = "376"),
        DialCountry(iso2 = "AO", name = "Angola", dialCode = "244"),
        DialCountry(iso2 = "AI", name = "Anguilla", dialCode = "1264"),
        DialCountry(iso2 = "AG", name = "Antigua and Barbuda", dialCode = "1268"),
        DialCountry(iso2 = "AR", name = "Argentina", dialCode = "54"),
        DialCountry(iso2 = "AM", name = "Armenia", dialCode = "374"),
        DialCountry(iso2 = "AW", name = "Aruba", dialCode = "297"),
        DialCountry(iso2 = "AU", name = "Australia", dialCode = "61"),
        DialCountry(iso2 = "AT", name = "Austria", dialCode = "43"),
        DialCountry(iso2 = "AZ", name = "Azerbaijan", dialCode = "994"),
        DialCountry(iso2 = "BS", name = "Bahamas", dialCode = "1242"),
        DialCountry(iso2 = "BH", name = "Bahrain", dialCode = "973"),
        DialCountry(iso2 = "BD", name = "Bangladesh", dialCode = "880"),
        DialCountry(iso2 = "BB", name = "Barbados", dialCode = "1246"),
        DialCountry(iso2 = "BY", name = "Belarus", dialCode = "375"),
        DialCountry(iso2 = "BE", name = "Belgium", dialCode = "32"),
        DialCountry(iso2 = "BZ", name = "Belize", dialCode = "501"),
        DialCountry(iso2 = "BJ", name = "Benin", dialCode = "229"),
        DialCountry(iso2 = "BM", name = "Bermuda", dialCode = "1441"),
        DialCountry(iso2 = "BT", name = "Bhutan", dialCode = "975"),
        DialCountry(iso2 = "BO", name = "Bolivia", dialCode = "591"),
        DialCountry(iso2 = "BA", name = "Bosnia and Herzegovina", dialCode = "387"),
        DialCountry(iso2 = "BW", name = "Botswana", dialCode = "267"),
        DialCountry(iso2 = "BV", name = "Bouvet Island", dialCode = "47"),
        DialCountry(iso2 = "BR", name = "Brazil", dialCode = "55"),
        DialCountry(iso2 = "IO", name = "British Indian Ocean Territory", dialCode = "246"),
        DialCountry(iso2 = "VG", name = "British Virgin Islands", dialCode = "1284"),
        DialCountry(iso2 = "BN", name = "Brunei", dialCode = "673"),
        DialCountry(iso2 = "BG", name = "Bulgaria", dialCode = "359"),
        DialCountry(iso2 = "BF", name = "Burkina Faso", dialCode = "226"),
        DialCountry(iso2 = "BI", name = "Burundi", dialCode = "257"),
        DialCountry(iso2 = "KH", name = "Cambodia", dialCode = "855"),
        DialCountry(iso2 = "CM", name = "Cameroon", dialCode = "237"),
        DialCountry(iso2 = "CA", name = "Canada", dialCode = "1"),
        DialCountry(iso2 = "CV", name = "Cape Verde", dialCode = "238"),
        DialCountry(iso2 = "BQ", name = "Caribbean Netherlands", dialCode = "599"),
        DialCountry(iso2 = "KY", name = "Cayman Islands", dialCode = "1345"),
        DialCountry(iso2 = "CF", name = "Central African Republic", dialCode = "236"),
        DialCountry(iso2 = "TD", name = "Chad", dialCode = "235"),
        DialCountry(iso2 = "CL", name = "Chile", dialCode = "56"),
        DialCountry(iso2 = "CN", name = "China", dialCode = "86"),
        DialCountry(iso2 = "CX", name = "Christmas Island", dialCode = "61"),
        DialCountry(iso2 = "CC", name = "Cocos (Keeling) Islands", dialCode = "61"),
        DialCountry(iso2 = "CO", name = "Colombia", dialCode = "57"),
        DialCountry(iso2 = "KM", name = "Comoros", dialCode = "269"),
        DialCountry(iso2 = "CK", name = "Cook Islands", dialCode = "682"),
        DialCountry(iso2 = "CR", name = "Costa Rica", dialCode = "506"),
        DialCountry(iso2 = "HR", name = "Croatia", dialCode = "385"),
        DialCountry(iso2 = "CU", name = "Cuba", dialCode = "53"),
        DialCountry(iso2 = "CW", name = "Curaçao", dialCode = "599"),
        DialCountry(iso2 = "CY", name = "Cyprus", dialCode = "357"),
        DialCountry(iso2 = "CZ", name = "Czechia", dialCode = "420"),
        DialCountry(iso2 = "CI", name = "Côte d'Ivoire", dialCode = "225"),
        DialCountry(iso2 = "DK", name = "Denmark", dialCode = "45"),
        DialCountry(iso2 = "DJ", name = "Djibouti", dialCode = "253"),
        DialCountry(iso2 = "DM", name = "Dominica", dialCode = "1767"),
        DialCountry(iso2 = "DO", name = "Dominican Republic", dialCode = "1"),
        DialCountry(iso2 = "CD", name = "DR Congo", dialCode = "243"),
        DialCountry(iso2 = "EC", name = "Ecuador", dialCode = "593"),
        DialCountry(iso2 = "EG", name = "Egypt", dialCode = "20"),
        DialCountry(iso2 = "SV", name = "El Salvador", dialCode = "503"),
        DialCountry(iso2 = "GQ", name = "Equatorial Guinea", dialCode = "240"),
        DialCountry(iso2 = "ER", name = "Eritrea", dialCode = "291"),
        DialCountry(iso2 = "EE", name = "Estonia", dialCode = "372"),
        DialCountry(iso2 = "SZ", name = "Eswatini", dialCode = "268"),
        DialCountry(iso2 = "ET", name = "Ethiopia", dialCode = "251"),
        DialCountry(iso2 = "FK", name = "Falkland Islands", dialCode = "500"),
        DialCountry(iso2 = "FO", name = "Faroe Islands", dialCode = "298"),
        DialCountry(iso2 = "FJ", name = "Fiji", dialCode = "679"),
        DialCountry(iso2 = "FI", name = "Finland", dialCode = "358"),
        DialCountry(iso2 = "FR", name = "France", dialCode = "33"),
        DialCountry(iso2 = "GF", name = "French Guiana", dialCode = "594"),
        DialCountry(iso2 = "PF", name = "French Polynesia", dialCode = "689"),
        DialCountry(iso2 = "TF", name = "French Southern and Antarctic Lands", dialCode = "262"),
        DialCountry(iso2 = "GA", name = "Gabon", dialCode = "241"),
        DialCountry(iso2 = "GM", name = "Gambia", dialCode = "220"),
        DialCountry(iso2 = "GE", name = "Georgia", dialCode = "995"),
        DialCountry(iso2 = "DE", name = "Germany", dialCode = "49"),
        DialCountry(iso2 = "GH", name = "Ghana", dialCode = "233"),
        DialCountry(iso2 = "GI", name = "Gibraltar", dialCode = "350"),
        DialCountry(iso2 = "GR", name = "Greece", dialCode = "30"),
        DialCountry(iso2 = "GL", name = "Greenland", dialCode = "299"),
        DialCountry(iso2 = "GD", name = "Grenada", dialCode = "1473"),
        DialCountry(iso2 = "GP", name = "Guadeloupe", dialCode = "590"),
        DialCountry(iso2 = "GU", name = "Guam", dialCode = "1671"),
        DialCountry(iso2 = "GT", name = "Guatemala", dialCode = "502"),
        DialCountry(iso2 = "GG", name = "Guernsey", dialCode = "44"),
        DialCountry(iso2 = "GN", name = "Guinea", dialCode = "224"),
        DialCountry(iso2 = "GW", name = "Guinea-Bissau", dialCode = "245"),
        DialCountry(iso2 = "GY", name = "Guyana", dialCode = "592"),
        DialCountry(iso2 = "HT", name = "Haiti", dialCode = "509"),
        DialCountry(iso2 = "HN", name = "Honduras", dialCode = "504"),
        DialCountry(iso2 = "HK", name = "Hong Kong", dialCode = "852"),
        DialCountry(iso2 = "HU", name = "Hungary", dialCode = "36"),
        DialCountry(iso2 = "IS", name = "Iceland", dialCode = "354"),
        DialCountry(iso2 = "IN", name = "India", dialCode = "91"),
        DialCountry(iso2 = "ID", name = "Indonesia", dialCode = "62"),
        DialCountry(iso2 = "IR", name = "Iran", dialCode = "98"),
        DialCountry(iso2 = "IQ", name = "Iraq", dialCode = "964"),
        DialCountry(iso2 = "IE", name = "Ireland", dialCode = "353"),
        DialCountry(iso2 = "IM", name = "Isle of Man", dialCode = "44"),
        DialCountry(iso2 = "IL", name = "Israel", dialCode = "972"),
        DialCountry(iso2 = "IT", name = "Italy", dialCode = "39"),
        DialCountry(iso2 = "JM", name = "Jamaica", dialCode = "1876"),
        DialCountry(iso2 = "JP", name = "Japan", dialCode = "81"),
        DialCountry(iso2 = "JE", name = "Jersey", dialCode = "44"),
        DialCountry(iso2 = "JO", name = "Jordan", dialCode = "962"),
        DialCountry(iso2 = "KZ", name = "Kazakhstan", dialCode = "7"),
        DialCountry(iso2 = "KE", name = "Kenya", dialCode = "254"),
        DialCountry(iso2 = "KI", name = "Kiribati", dialCode = "686"),
        DialCountry(iso2 = "XK", name = "Kosovo", dialCode = "383"),
        DialCountry(iso2 = "KW", name = "Kuwait", dialCode = "965"),
        DialCountry(iso2 = "KG", name = "Kyrgyzstan", dialCode = "996"),
        DialCountry(iso2 = "LA", name = "Laos", dialCode = "856"),
        DialCountry(iso2 = "LV", name = "Latvia", dialCode = "371"),
        DialCountry(iso2 = "LB", name = "Lebanon", dialCode = "961"),
        DialCountry(iso2 = "LS", name = "Lesotho", dialCode = "266"),
        DialCountry(iso2 = "LR", name = "Liberia", dialCode = "231"),
        DialCountry(iso2 = "LY", name = "Libya", dialCode = "218"),
        DialCountry(iso2 = "LI", name = "Liechtenstein", dialCode = "423"),
        DialCountry(iso2 = "LT", name = "Lithuania", dialCode = "370"),
        DialCountry(iso2 = "LU", name = "Luxembourg", dialCode = "352"),
        DialCountry(iso2 = "MO", name = "Macau", dialCode = "853"),
        DialCountry(iso2 = "MG", name = "Madagascar", dialCode = "261"),
        DialCountry(iso2 = "MW", name = "Malawi", dialCode = "265"),
        DialCountry(iso2 = "MY", name = "Malaysia", dialCode = "60"),
        DialCountry(iso2 = "MV", name = "Maldives", dialCode = "960"),
        DialCountry(iso2 = "ML", name = "Mali", dialCode = "223"),
        DialCountry(iso2 = "MT", name = "Malta", dialCode = "356"),
        DialCountry(iso2 = "MH", name = "Marshall Islands", dialCode = "692"),
        DialCountry(iso2 = "MQ", name = "Martinique", dialCode = "596"),
        DialCountry(iso2 = "MR", name = "Mauritania", dialCode = "222"),
        DialCountry(iso2 = "MU", name = "Mauritius", dialCode = "230"),
        DialCountry(iso2 = "YT", name = "Mayotte", dialCode = "262"),
        DialCountry(iso2 = "MX", name = "Mexico", dialCode = "52"),
        DialCountry(iso2 = "FM", name = "Micronesia", dialCode = "691"),
        DialCountry(iso2 = "MD", name = "Moldova", dialCode = "373"),
        DialCountry(iso2 = "MC", name = "Monaco", dialCode = "377"),
        DialCountry(iso2 = "MN", name = "Mongolia", dialCode = "976"),
        DialCountry(iso2 = "ME", name = "Montenegro", dialCode = "382"),
        DialCountry(iso2 = "MS", name = "Montserrat", dialCode = "1664"),
        DialCountry(iso2 = "MA", name = "Morocco", dialCode = "212"),
        DialCountry(iso2 = "MZ", name = "Mozambique", dialCode = "258"),
        DialCountry(iso2 = "MM", name = "Myanmar", dialCode = "95"),
        DialCountry(iso2 = "NA", name = "Namibia", dialCode = "264"),
        DialCountry(iso2 = "NR", name = "Nauru", dialCode = "674"),
        DialCountry(iso2 = "NP", name = "Nepal", dialCode = "977"),
        DialCountry(iso2 = "NL", name = "Netherlands", dialCode = "31"),
        DialCountry(iso2 = "NC", name = "New Caledonia", dialCode = "687"),
        DialCountry(iso2 = "NZ", name = "New Zealand", dialCode = "64"),
        DialCountry(iso2 = "NI", name = "Nicaragua", dialCode = "505"),
        DialCountry(iso2 = "NE", name = "Niger", dialCode = "227"),
        DialCountry(iso2 = "NG", name = "Nigeria", dialCode = "234"),
        DialCountry(iso2 = "NU", name = "Niue", dialCode = "683"),
        DialCountry(iso2 = "NF", name = "Norfolk Island", dialCode = "672"),
        DialCountry(iso2 = "KP", name = "North Korea", dialCode = "850"),
        DialCountry(iso2 = "MK", name = "North Macedonia", dialCode = "389"),
        DialCountry(iso2 = "MP", name = "Northern Mariana Islands", dialCode = "1670"),
        DialCountry(iso2 = "NO", name = "Norway", dialCode = "47"),
        DialCountry(iso2 = "OM", name = "Oman", dialCode = "968"),
        DialCountry(iso2 = "PK", name = "Pakistan", dialCode = "92"),
        DialCountry(iso2 = "PW", name = "Palau", dialCode = "680"),
        DialCountry(iso2 = "PS", name = "Palestine", dialCode = "970"),
        DialCountry(iso2 = "PA", name = "Panama", dialCode = "507"),
        DialCountry(iso2 = "PG", name = "Papua New Guinea", dialCode = "675"),
        DialCountry(iso2 = "PY", name = "Paraguay", dialCode = "595"),
        DialCountry(iso2 = "PE", name = "Peru", dialCode = "51"),
        DialCountry(iso2 = "PH", name = "Philippines", dialCode = "63"),
        DialCountry(iso2 = "PN", name = "Pitcairn Islands", dialCode = "64"),
        DialCountry(iso2 = "PL", name = "Poland", dialCode = "48"),
        DialCountry(iso2 = "PT", name = "Portugal", dialCode = "351"),
        DialCountry(iso2 = "PR", name = "Puerto Rico", dialCode = "1"),
        DialCountry(iso2 = "QA", name = "Qatar", dialCode = "974"),
        DialCountry(iso2 = "CG", name = "Republic of the Congo", dialCode = "242"),
        DialCountry(iso2 = "RO", name = "Romania", dialCode = "40"),
        DialCountry(iso2 = "RU", name = "Russia", dialCode = "7"),
        DialCountry(iso2 = "RW", name = "Rwanda", dialCode = "250"),
        DialCountry(iso2 = "RE", name = "Réunion", dialCode = "262"),
        DialCountry(iso2 = "BL", name = "Saint Barthélemy", dialCode = "590"),
        DialCountry(iso2 = "SH", name = "Saint Helena", dialCode = "290"),
        DialCountry(iso2 = "KN", name = "Saint Kitts and Nevis", dialCode = "1869"),
        DialCountry(iso2 = "LC", name = "Saint Lucia", dialCode = "1758"),
        DialCountry(iso2 = "MF", name = "Saint Martin", dialCode = "590"),
        DialCountry(iso2 = "PM", name = "Saint Pierre and Miquelon", dialCode = "508"),
        DialCountry(iso2 = "VC", name = "Saint Vincent and the Grenadines", dialCode = "1784"),
        DialCountry(iso2 = "WS", name = "Samoa", dialCode = "685"),
        DialCountry(iso2 = "SM", name = "San Marino", dialCode = "378"),
        DialCountry(iso2 = "SA", name = "Saudi Arabia", dialCode = "966"),
        DialCountry(iso2 = "SN", name = "Senegal", dialCode = "221"),
        DialCountry(iso2 = "RS", name = "Serbia", dialCode = "381"),
        DialCountry(iso2 = "SC", name = "Seychelles", dialCode = "248"),
        DialCountry(iso2 = "SL", name = "Sierra Leone", dialCode = "232"),
        DialCountry(iso2 = "SG", name = "Singapore", dialCode = "65"),
        DialCountry(iso2 = "SX", name = "Sint Maarten", dialCode = "1721"),
        DialCountry(iso2 = "SK", name = "Slovakia", dialCode = "421"),
        DialCountry(iso2 = "SI", name = "Slovenia", dialCode = "386"),
        DialCountry(iso2 = "SB", name = "Solomon Islands", dialCode = "677"),
        DialCountry(iso2 = "SO", name = "Somalia", dialCode = "252"),
        DialCountry(iso2 = "ZA", name = "South Africa", dialCode = "27"),
        DialCountry(iso2 = "GS", name = "South Georgia", dialCode = "500"),
        DialCountry(iso2 = "KR", name = "South Korea", dialCode = "82"),
        DialCountry(iso2 = "SS", name = "South Sudan", dialCode = "211"),
        DialCountry(iso2 = "ES", name = "Spain", dialCode = "34"),
        DialCountry(iso2 = "LK", name = "Sri Lanka", dialCode = "94"),
        DialCountry(iso2 = "SD", name = "Sudan", dialCode = "249"),
        DialCountry(iso2 = "SR", name = "Suriname", dialCode = "597"),
        DialCountry(iso2 = "SJ", name = "Svalbard and Jan Mayen", dialCode = "4779"),
        DialCountry(iso2 = "SE", name = "Sweden", dialCode = "46"),
        DialCountry(iso2 = "CH", name = "Switzerland", dialCode = "41"),
        DialCountry(iso2 = "SY", name = "Syria", dialCode = "963"),
        DialCountry(iso2 = "ST", name = "São Tomé and Príncipe", dialCode = "239"),
        DialCountry(iso2 = "TW", name = "Taiwan", dialCode = "886"),
        DialCountry(iso2 = "TJ", name = "Tajikistan", dialCode = "992"),
        DialCountry(iso2 = "TZ", name = "Tanzania", dialCode = "255"),
        DialCountry(iso2 = "TH", name = "Thailand", dialCode = "66"),
        DialCountry(iso2 = "TL", name = "Timor-Leste", dialCode = "670"),
        DialCountry(iso2 = "TG", name = "Togo", dialCode = "228"),
        DialCountry(iso2 = "TK", name = "Tokelau", dialCode = "690"),
        DialCountry(iso2 = "TO", name = "Tonga", dialCode = "676"),
        DialCountry(iso2 = "TT", name = "Trinidad and Tobago", dialCode = "1868"),
        DialCountry(iso2 = "TN", name = "Tunisia", dialCode = "216"),
        DialCountry(iso2 = "TM", name = "Turkmenistan", dialCode = "993"),
        DialCountry(iso2 = "TC", name = "Turks and Caicos Islands", dialCode = "1649"),
        DialCountry(iso2 = "TV", name = "Tuvalu", dialCode = "688"),
        DialCountry(iso2 = "TR", name = "Türkiye", dialCode = "90"),
        DialCountry(iso2 = "UG", name = "Uganda", dialCode = "256"),
        DialCountry(iso2 = "UA", name = "Ukraine", dialCode = "380"),
        DialCountry(iso2 = "AE", name = "United Arab Emirates", dialCode = "971"),
        DialCountry(iso2 = "GB", name = "United Kingdom", dialCode = "44"),
        DialCountry(iso2 = "US", name = "United States", dialCode = "1"),
        DialCountry(iso2 = "VI", name = "United States Virgin Islands", dialCode = "1340"),
        DialCountry(iso2 = "UY", name = "Uruguay", dialCode = "598"),
        DialCountry(iso2 = "UZ", name = "Uzbekistan", dialCode = "998"),
        DialCountry(iso2 = "VU", name = "Vanuatu", dialCode = "678"),
        DialCountry(iso2 = "VA", name = "Vatican City", dialCode = "39"),
        DialCountry(iso2 = "VE", name = "Venezuela", dialCode = "58"),
        DialCountry(iso2 = "VN", name = "Vietnam", dialCode = "84"),
        DialCountry(iso2 = "WF", name = "Wallis and Futuna", dialCode = "681"),
        DialCountry(iso2 = "EH", name = "Western Sahara", dialCode = "212"),
        DialCountry(iso2 = "YE", name = "Yemen", dialCode = "967"),
        DialCountry(iso2 = "ZM", name = "Zambia", dialCode = "260"),
        DialCountry(iso2 = "ZW", name = "Zimbabwe", dialCode = "263"),
        DialCountry(iso2 = "AX", name = "Åland Islands", dialCode = "35818"),
    )

    private val byIso: Map<String, DialCountry> = all.associateBy { it.iso2 }

    fun byIso2(iso2: String?): DialCountry? = iso2?.uppercase()?.let { byIso[it] }

    /** Countries whose dial code equals [dialCode], the most common one first (US before CA for "1"). */
    fun byDialCode(dialCode: String): List<DialCountry> {
        val matches = all.filter { it.dialCode == dialCode }
        val preferred = setOf("US", "RU", "ID", "IN", "GB", "AU", "NO", "FR", "ES", "IT", "DE", "SA")
        return matches.sortedByDescending { it.iso2 in preferred }
    }

    /** Longest dial code that prefixes [digits] (so "1684..." resolves to American Samoa before the US). */
    fun longestPrefixMatch(digits: String): DialCountry? {
        var best: DialCountry? = null
        for (c in all) {
            if (digits.startsWith(c.dialCode) && (best == null || c.dialCode.length > best.dialCode.length)) {
                best = byDialCode(c.dialCode).first()
            }
        }
        return best
    }
}
