#!/usr/bin/env python3
"""Generate LucideIcons.kt (enum of SVG path strings) from Lucide SVG files.

Usage: python3 tools/lucide_gen.py <svg-dir> <output.kt>
Lucide icons are ISC licensed (see docs/licenses/LICENSE-lucide.txt).
"""
import sys, os, re, xml.etree.ElementTree as ET

NS = '{http://www.w3.org/2000/svg}'

def num(v, d='0'):
    return float(v if v is not None else d)

def fmt(f):
    s = ('%.3f' % f).rstrip('0').rstrip('.')
    return s if s != '-0' else '0'

def el_to_path(el):
    tag = el.tag.replace(NS, '')
    a = el.attrib
    if tag == 'path':
        return a['d'].strip()
    if tag == 'circle':
        cx, cy, r = num(a.get('cx')), num(a.get('cy')), num(a.get('r'))
        return f"M{fmt(cx - r)} {fmt(cy)}a{fmt(r)} {fmt(r)} 0 1 0 {fmt(2*r)} 0a{fmt(r)} {fmt(r)} 0 1 0 {fmt(-2*r)} 0"
    if tag == 'ellipse':
        cx, cy, rx, ry = num(a.get('cx')), num(a.get('cy')), num(a.get('rx')), num(a.get('ry'))
        return f"M{fmt(cx - rx)} {fmt(cy)}a{fmt(rx)} {fmt(ry)} 0 1 0 {fmt(2*rx)} 0a{fmt(rx)} {fmt(ry)} 0 1 0 {fmt(-2*rx)} 0"
    if tag == 'rect':
        x, y, w, h = num(a.get('x')), num(a.get('y')), num(a.get('width')), num(a.get('height'))
        rx = num(a.get('rx'), a.get('ry', '0')); ry = num(a.get('ry'), a.get('rx', '0'))
        if rx == 0 and ry == 0:
            return f"M{fmt(x)} {fmt(y)}h{fmt(w)}v{fmt(h)}h{fmt(-w)}z"
        return (f"M{fmt(x+rx)} {fmt(y)}h{fmt(w-2*rx)}a{fmt(rx)} {fmt(ry)} 0 0 1 {fmt(rx)} {fmt(ry)}"
                f"v{fmt(h-2*ry)}a{fmt(rx)} {fmt(ry)} 0 0 1 {fmt(-rx)} {fmt(ry)}h{fmt(-(w-2*rx))}"
                f"a{fmt(rx)} {fmt(ry)} 0 0 1 {fmt(-rx)} {fmt(-ry)}v{fmt(-(h-2*ry))}a{fmt(rx)} {fmt(ry)} 0 0 1 {fmt(rx)} {fmt(-ry)}z")
    if tag == 'line':
        return f"M{fmt(num(a.get('x1')))} {fmt(num(a.get('y1')))}L{fmt(num(a.get('x2')))} {fmt(num(a.get('y2')))}"
    if tag in ('polyline', 'polygon'):
        pts = [float(p) for p in re.split(r'[\s,]+', a['points'].strip()) if p]
        pairs = list(zip(pts[0::2], pts[1::2]))
        d = 'M' + 'L'.join(f"{fmt(x)} {fmt(y)}" for x, y in pairs)
        return d + ('z' if tag == 'polygon' else '')
    raise ValueError('unsupported element ' + tag)

def pascal(name):
    return ''.join(p[:1].upper() + p[1:] for p in name.split('-'))

def main(svg_dir, out):
    entries = []
    for fn in sorted(os.listdir(svg_dir)):
        if not fn.endswith('.svg'):
            continue
        root = ET.parse(os.path.join(svg_dir, fn)).getroot()
        paths = [el_to_path(el) for el in root]
        name = fn[:-4]
        entries.append((pascal(name), name, paths))
    with open(out, 'w') as f:
        f.write('package com.piptechnologies.openchat.ui.icons\n\n')
        f.write('// GENERATED by tools/lucide_gen.py from Lucide SVGs (ISC license, docs/licenses/LICENSE-lucide.txt).\n')
        f.write('// Do not edit by hand. Each entry is the icon\'s SVG path data in a 24x24 viewport.\n\n')
        f.write('enum class LucideIcon(val iconName: String, val paths: List<String>) {\n')
        for i, (k, name, paths) in enumerate(entries):
            ps = ', '.join('"' + p.replace('"', '\\"') + '"' for p in paths)
            sep = ',' if i < len(entries) - 1 else ';'
            f.write(f'    {k}("{name}", listOf({ps})){sep}\n')
        f.write('}\n')
    print('wrote', out, len(entries), 'icons')

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
